//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWGetNumberOfTeachersByStandard
    {
        public long ID { get; set; }
        public Nullable<int> StandardId { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
